### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#120]
Once the model directory structure is decided on, automatically generate documentation
- [x] search `Models` folder and create instance in .rst
- [x] search `Data` folder for associated batch examples
   - [x] naming convention has to be `Model_batch.m`
- [x] generate html for batch example and insert reference into .rst
- [x] follow the format for the web as is #117 
- [x] fix font issue #109 
- [x] verify it all works with ReadTheDocs #57 
- [x] merge jca_help #84 
- [x] fill in all assumptions #55 
- [x] Color MRIinputs in the GUI #83 

- [x] Update the video @nstikov 

- [x] Developer documentation to be added in Wiki  #128 @agahkarakuzu

**Comment by gab-berest** [comment]
The automatic toctree script is finished and working on my branch. I think it can be merged @tanguyduval . If the naming convention is respected and the batch is working, it will work and add it to the toctree and create the .rst files

**Comment by ileppe** [comment]
I've overhauled some of the documentation in this branch 'new-doc'. It might break the automatic toc tree script so didn't want to push to 'doc' yet. I would appreciate your comments at this point, would still need to be polished: pls check here: `http://qmrlab.readthedocs.io/en/new-doc/`
@jcohenadad : I modified the `getting started` section, please let me know what you think
@nstikov : I added captions for the menus, is the menu flipping less annoying?
@tanguyduval : I'd like your input, specifically on the `general usage guidelines` section
@mathieuboudreau @agahkarakuzu : Any input would be great!
Thanks!

**Comment by mathieuboudreau** [comment]
@ileppe The `Getting Started` section looks fantastic! I think this is spot on towards what Julien was suggesting. Great job!

I will give it a go and try to follow the instructions sometimes this week and report back if there are any clarifications in the instructions I think should be made.

**Comment by ileppe** [comment]
@mathieuboudreau thanks! you're awesome!

**Comment by jcohenadad** [comment]
@ileppe the Getting Started section is AWESOME!!!  Thank you so much for your creativity and efforts to make the documentation an intuitive and easy starting point to every user of qMRLab!

**Comment by mathieuboudreau** [comment]
@ileppe I went through the instructions, here are some general thoughts (both about the instructions and the user experience I went through):

1. (In Step 3) I looked at the code, and downloadData(Model, []) works without the `[]` second argument (e.g. `downloadData(Model)`). We should probably use that in the instructions since it's "cleaner" and lead to less confusion for the new users about what the brackets are for.

2. (In Step 6) Loading the data is automatic when selecting the working dir, but may not be clear to the user why. It works because the files followed a naming convention, but we should briefly point out a few additional things in the instructions:

	* The naming convention is not strictly necessary, the files could be loaded one by one otherwise.
	* In that case, the working directory is the directory the location where processed files will be saved.
	* Where can the user find the file naming convention for each model in case we want them to be loaded automatically? (@tanguyduval @agahkarakuzu where is this file naming convention documented? I clicked on the Data Format link that Ilana gave in her instructions, and there it suggests to do `help vfa_t1` to find out, but the file naming convention is not explicitly stated there. @IanGagnon7 Is there supposed to be a section in the model doc that states the data file naming conventions so that the automated data loading per Ilana's instruction may be used? If so we should check that all the models contain this important information).

3. (In Step 8) One VFA-side minor issue: The units of the required protocol parameters should be displayed in the GUI (e.g. degrees for FA, (s) for TR). @IanGagnon7 
	
4. One issue I encountered was that the histogram currently does not omit the points that should be masked out by the mask. (e.g. for the B1 map, there are thousands of points in the histogram at a value of exactly 1, which is what the masked values of B1 outside the brain were set at). @agahkarakuzu The histogram calculation should be changed to use the mask omit this data before it is calculated.

5. @agahkarakuzu Save figure gives an error when when trying to save the loaded data as figs files if the save figure button is pressed prior to fitting the data. This happens at this stage because the "FitResults" folder was not created yet, and "save figure" tries to save directly in this folder regardless. So there should be an if ~exists somewhere here for the gui to create that folder if it doesn't exist yet so that users can save the raw data as matlab figs, or ideally change the location of the save figure files to another folder, since it is only related to the fit results in the case that this is the data that wants to be saved (which is not the only case for use of this button).

6. (In Step 9) @IanGagnon7 @agahkarakuzu Concerning the "View data fit" graph for VFA, it would make sense to include the fitted values here (or at least, T1). Right now only the linear curve is shown, which is not useful without knowing the T1 value that was fitted.

7. (In Step 10) After the users are instructed to fit the data, we should add a note in the example instructions that the data is saved locally (both as *.mat files and *.nii.gz (compressed NIfTI files).

**Comment by tanguyduval** [comment]
@mathieuboudreau thanks for all these modifications.
Concerning point 2., I see in BrowserSet.m the line `if strfind(fileList{i}(1:end-4), DataName{1})`

So, when browsing the WD, qMRLab searches for the pattern `MRIinputs` (e.g. `Mask`) in the filename (cropped by 4 characters in order to remove the extension). Strfind is case sensitive.
Example:
`MyCustomMask.nii.gz`, `MyCustomMask.nii`, `MyCustomMask.mat`, `MyCustomMask2.nii.gz` will be filled in field `Mask`
`MyCustommask.nii.gz`, will NOT be filled in `Mask`

Pascale wrote the code for this if you need more info.

**Comment by mathieuboudreau** [comment]
@tanguyduval Ah ha, thanks for finding that and clearing it up for me! This rule should likely be spelled out clearly in either the header of the Model and/or the documentation section, particularly the case-sensitive feature of the regex pattern search.

A+

**Comment by agahkarakuzu** [comment]
@ileppe I loved Getting Started section! It is super intuitive, I followed all the steps from scratch and it worked as charm. 

@mathieuboudreau I will upload all FitResults to the OSF and make a small modification on downloadData. This should cease the problem completely.  I will also go through your remaining mentions. Thank you so much for the feedback!

**Comment by tanguyduval** [comment]
@ileppe I went through the general usage guidelines in a49150e666500bf1e1e7c7621e42822e341c5b7f

Also, I solved the crash of Travis.

I propose to merge current new-doc branch, and keep this issue open.

**Comment by agahkarakuzu** [comment]
All these issues seem to be resolved. I will close this issue in few days unless someone thinks otherwise.

**Comment by mathieuboudreau** [comment]
All the initial to-dos were dealt with, so I'm closing it now. Smaller documentation improvement requests can be made in individual issues from this point on.
