### ISSUE TITLE
Mathieu To-Do

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#43]
Sharing my to-do list of tasks I plan on doing during some of my free time, usually Friday afternoons (for [Open Source Fridays!](https://opensourcefriday.com)).

- If you notice that I'm working on any files that are removed or changed in a branch you're working on, let me know which branch/file so that I can redirect my work.

- If you have any suggestions to add on my To-Do list, let me know in a comment below.

## Tests
I plan on writing unit or integration tests for the following functions/files:

- [x] [Common/sim/computeR1.m](https://github.com/neuropoly/qMRLab/blob/6d5535bf7f908e1079bf169e43cb705041441f66/Common/sim/computeR1.m)
- [x] [Common/sim/BlochNoMT.m](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/BlochNoMT.m)
- [x] [Common/sim/Bloch.m](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/BlochSol.m)
- [x] [Common/sim/BlochSol.m](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/BlochSol.m)

## Refactor

- [x] Replace hard-coded R1f calculations (e.g. [here_1](https://github.com/neuropoly/qMRLab/blob/d2196234d31fc938fdf33bf6406df3d39da13940/Models_Functions/SPGRfun/functions/SPGR_R_fun.m#L25) and [here_2](https://github.com/neuropoly/qMRLab/blob/5bf8989d26ca5df52e1608d46ba2958be12a4324/Models_Functions/SIRFSEfun/functions/SIRFSE_fit.m#L61)) by calls to the existing function [computeR1.m](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/computeR1.m).
- [ ] Resolve the naming conflict between [computeR1.m](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/computeR1.m) (which calculates R1f), and the FitOpt struct field R1 (which actually represents R1obs, as calculated [here_1](https://github.com/neuropoly/qMRLab/blob/3fac797194ddb850ba2666cde644a5b864f98b4e/Models_Functions/SPGRfun/SimDemo_SPGR.m#L7), [here_2](https://github.com/neuropoly/qMRLab/blob/3fac797194ddb850ba2666cde644a5b864f98b4e/Common/sim/VaryParamPar.m#L100), [here_3](https://github.com/neuropoly/qMRLab/blob/3fac797194ddb850ba2666cde644a5b864f98b4e/Common/sim/VaryRndParam.m#L62), [here_4](https://github.com/neuropoly/qMRLab/blob/3fac797194ddb850ba2666cde644a5b864f98b4e/Common/sim/VaryParam.m#L99), and [here_5](https://github.com/neuropoly/qMRLab/blob/3837121d189f10e3af00bc85de4c25e31a4237f3/qMRILab.m#L465)).
- [ ] Switch kr->kf as a default SPGR qMT fit option parameter, which is more used (kf = F*kr).
- [ ] Move G outside of the Param structs, and instead calculated it within the Bloch and BlochSol functions. Right now, Bloch/BlochSol take delta as a param, but it's already needed to calculate G. Keeping them separate like this could lead to a delta mismatch between G and the Bloch/BlochSol delta arguments.

## Documentation

- [x] Write help documentation for Common/pulse/*.m functions.
- [x] Write help documentation for Common/sim/Bloch*.m functions.
- [ ] Add paper references to relevant qMT equations/functions.

## Bug fixes

- [x] Fix issue where [Common/sim/BlochSol.m](https://github.com/neuropoly/qMRLab/blob/6d5535bf7f908e1079bf169e43cb705041441f66/Common/sim/BlochSol.m) returns a magnetization vector of type **single** even when the initial magnetization is of type **double**. Discovered while writing unit tests for this function.

**Comment by tanguyduval** [comment]
Hey Matthieu,

Ian's branch is ready (except Sr IRFSE). I checked out all changes on the original qMT files. Maybe you could work on a clone of Ian's branch because it's the most up to date (much more up to date than Master). Also you will be able to report any bug!

Best,
Tanguy

**Comment by mathieuboudreau** [comment]
I took a look at it; it seems like the files I'm currently interested with working on (see list) are not substantially different in his branch. I'll write the tests for the current master, and they should still pass once he merges his branch (otherwise we'll see how they differed from the original files, and if any bugs were accidentally introduced).

That way, I might merge the tests from master to his branch so I can compare how they performed.

Thanks for the update!

Mathieu

**Comment by agahkarakuzu** [comment]
@mathieuboudreau are you done with this to-do list? ✅
