### ISSUE TITLE
Gabriel todo

### ISSUE THREAD

**Issue by tanguyduval** [qMRLab/qMRLab#66]
- [x] clean examples, publish and integrate in sphinx
- [x] investigate compatibility with Octave
- [x] qMRLab change window position on opening
- [ ] add push button on Protocol Optimization plot (CRLB) to stop migrations
- [ ] compute G(0) in IRFSE and bSSFP
- [ ] add legend for single voxel curves (circles vs cross?)
- [x] add qMRusage in a parent class qMRMETHOD (if possible)
- [ ] work on CPU parallelization (to avoid looping across single voxels)
- [x] add test to check if all methods can be called without inputs
- [ ] Add module to generate protocols
- [ ] sinc --> rename because it's a core matlab function

**Comment by tanguyduval** [comment]
Example of code in `Documentation/source/conf.py` used to generate embed html of the demo:
`````
import xml.etree.ElementTree
fn = os.path.join(os.path.dirname(__file__), 'CHARMEDhtml/CHARMED_batch.html')

#tree = xml.etree.ElementTree.parse(
import io
with io.open("generated.rst", "wb") as f:
    #body = xml.etree.ElementTree.tostring(tree[0][1])
    t = "CHARMED"
    f.write(t.encode())
    f.write(b"\n")
    f.write(b"=" * len(t))
    f.write(b"\n")
    f.write(b"\n")
    f.write(b".. raw:: html\n")
    f.write(b"\n   \n")
    #f.write(("  %s" % body).encode("utf-8"))
    #f.write(b"   oihokh")
    with io.open(fn, "rb") as fi:
        for line in fi:
            f.write(b"   ")
            f.write(line)

`````

**Comment by gab-berest** [comment]
Information found on Octave compatibility function fmincon
Solutions:
1) function sqp(x0, phi) -> Not exactly the same as fmincon so might provoke errors if the code is not adapted
2)function nonlin_min (f, pin, settings) -> Same as before
3)download Optimization package for Octave forge with fmincon function

**Comment by ileppe** [comment]
In the `docs/source/conf.py`, don't forget to copy the .png generated by `publish` to the `docs/build/html` folder as well.

**Comment by gab-berest** [comment]
Yes, of course. But I might need your help next week because I'm able to publish almost all the models, but i cannot render the .rst file for sphinx. I have bugs that I don't find a way to solve.
